---
- name: 'Kubernetes | Create backup directory'
  file:
    path: '{{ k8s_etcd_backup_path }}'
    state: directory
    mode: '0755'


- name: 'Kubernetes | Create timer for Etcd backup'
  include_role: name=infra-role-systemd-timer
  vars:
    systemd_timer_description:    'dump etcd'
    systemd_timer_name:           '{{ k8s_etcd_backup_service_name }}'
    systemd_timer_user:           '{{ k8s_etcd_backup_user }}'
    systemd_timer_group:          '{{ k8s_etcd_backup_group }}'
    systemd_timer_frequency:      '{{ k8s_etcd_backup_frequency }}'
    systemd_timer_timeout_sec:    '{{ k8s_etcd_backup_timeout }}'
    systemd_timer_after_extra:    'docker.service'
    systemd_timer_start_on_creation: false
    systemd_timer_script_content: |
      #!/usr/bin/env bash
      bkp_dir={{ k8s_etcd_backup_path }}
      ETCDCTL_API=3 etcdctl snapshot save ${bkp_dir}/etcd-backup.db \
        --endpoints=https://127.0.0.1:2379 \
        --cert=/etc/kubernetes/pki/etcd/server.crt \
        --key=/etc/kubernetes/pki/etcd/server.key \
        --cacert=/etc/kubernetes/pki/etcd/ca.crt
      chmod 750 -R "${bkp_dir}"
