---
- name: 'Kubernetes | Create kubeadm config and basic deployment'
  template:
    src: '{{ item }}.j2'
    dest: '{{ k8s_service_path }}/{{ item }}'
  with_items:
    - 'kubeadm-config.yaml'
    - 'calico.yaml'
    - 'kubernetes-sigs.yaml'

- name: "Kubernetes | Install packages"
  apt:
    name: '{{ k8s_master_packages }}'
    state: present
    update_cache: true


- name: 'Kubernetes | Initialize the cluster'
  shell: 'kubeadm init --config /etc/kubernetes/kubeadm-config.yaml'

- name: 'Kubernetes | wait for API server to be up'
  wait_for: "host={{ k8s_master_ip }} port={{ k8s_master_api_server_port }} timeout=30"

- name: 'Kubernetes | Update admin config permission'
  file:
    path: '{{ k8s_service_path }}/admin.conf'
    owner: 'root'
    group: 'adm'
    mode: 0640

- name: 'Kubernetes | Install Pod Network'
  become: yes
  shell: 'kubectl apply -f {{ k8s_service_path }}/calico.yaml'
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'

- name: 'Kubernetes | Install nodes metrics'
  become: yes
  shell: 'kubectl apply -f {{ k8s_service_path }}/kubernetes-sigs.yaml'
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
