---
- import_tasks: install/main.yml
  tags: 'role::kubernetes:install'
  when: k8s_action == 'install'

- import_tasks: upgrade/main.yml
  tags: 'role::kubernetes:upgrade'
  when: k8s_action == 'upgrade'
