---
- name: 'Kub Upgrade | Cordon the node'
  shell: 'kubectl drain {{ ansible_hostname }} --ignore-daemonsets --delete-emptydir-data'
  become: false
  delegate_to: localhost

- name: 'Kub Upgrade | Install kubelet {{ k8s_upgrade_version }}'
  apt:
    name: kubelet={{ k8s_upgrade_version }}.*
    state: present
    allow_downgrade: yes
    update_cache: yes

- name: 'Kub Upgrade | Install kubectl {{ k8s_upgrade_version }}'
  apt:
    name: kubectl={{ k8s_upgrade_version }}.*
    state: present
    allow_downgrade: yes
    update_cache: yes

- name: 'Kub Upgrade | Reload systemd configuration'
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: 'kub Upgrade | restart kubelet'
  service:
    name: 'kubelet'
    state: 'restarted'
    enabled: true

- name: 'Kub Upgrade | uncordon node'
  shell: 'kubectl uncordon {{ ansible_hostname }}'
  delegate_to: localhost
  become: false
